CREATE TABLE product (
    id AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    description VARCHAR(100) NOT NULL,
    stock INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    rating DECIMAL(3, 2) NOT NULL,
    condition ENUM('NOU', 'BON_ESTAT', 'ACCEPTABLE', 'MAL_ESTAT') NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    dataCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dataUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);